

%: %.c
	mpicc $< -o $@

#so % pattern matches or anything, there is some nuance abt also using * but I'm not getting into that tbh
#flags is just so it's more readable 
#$@ is the target name and $< is the first prerequisite